### ISSUE TITLE
Improve rendering speed of RenderableSmallBody/RenderableSatellites

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1508] opened 2021-02-22 15:52 UTC
We have reports that Uniview is able to render 500k asteroids much faster then we are. 

Potentially there is room for improvement in how we render it.

**Comment by alexanderbock** [comment] 2023-06-01 06:41
Closing as duplicate of #2724

**Closed by alexanderbock** 2023-06-01 06:41 UTC
Labels: Type: Enhancement, Component: Rendering
