### ISSUE TITLE
ScreenSpaceRenderables - darker gamma then expected

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2503] opened 2023-02-13 17:02 UTC
When bringing in a slide, it comes out darker on the screen then the file if you just look at it in windows.

The same happens with skybrowser when looking at the CEF vs DisplayCopy

**Comment by alexanderbock** [comment] 2023-02-13 17:59
Closing as duplicate of #2504

**Closed by alexanderbock** 2023-02-13 17:59 UTC
