### ISSUE TITLE
OrbitAtConstantLat - Option for navigation

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2509] opened 2023-02-14 19:42 UTC
Right now, the idle has this nice behavior setting. 

I would desire to have this ability with the mouse, and with the websocket

Use case is that it keeps the 'map facing north'  as I sent left and right commands from some type of controller

**Comment by alexanderbock** [comment] 2023-02-21 16:37
Close as duplicate of #1372

**Closed by alexanderbock** 2023-02-21 16:37 UTC
Labels: Type: Enhancement, Component: Interaction
