### ISSUE TITLE
Moon not visible in foreground to sun during solar eclipse when in Earth's atmosphere

### ISSUE THREAD

**Issue by carteremmart** [OpenSpace/OpenSpace#1809] opened 2021-06-01 18:23 UTC
While investigating display options of eclipse shadowing on Earth during a solar eclipse, I observed that across the range of display options a consistent issue that within Earth's atmosphere, looking toward the sun that the moon does not appear in front of the sun.  Climbing above the atmosphere, the moon suddenly appears correctly in foreground to the Sun's glare and Sun's face.

![OpenSpace_000000](https://user-images.githubusercontent.com/70605329/120372203-d9f55c80-c2e4-11eb-83f3-22685fa75400.png)
![OpenSpace_000001](https://user-images.githubusercontent.com/70605329/120372243-e974a580-c2e4-11eb-83af-5ea32e21537a.png)

**Comment by micahnyc** [comment] 2022-01-06 16:04
lost the comment from Alex when transferring repos: "Worth checking if there is an issue with the scale"

**Comment by alexanderbock** [comment] 2023-03-14 09:46
Closing as duplicate of #1629

**Closed by alexanderbock** 2023-03-14 09:46 UTC
Labels: Type: Bug, Component: Rendering, Feature: Atmosphere
