### ISSUE TITLE
Focus Panel - extra selection of node

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2908] opened 2023-10-03 23:14 UTC
after selecting a focus node, if the panel is left open, and you press F, it retargets/centers the node

**Comment by micahnyc** [comment] 2023-10-03 23:18
(use case, you are zoomed in on jupiter, you zoomed out with shift+F, when at a solarsystem view, then you ctrl+shift+clicked on the sun to focus it while keeping momentum and not retargeting, then you pressed shift+f to take off the zoom but since you had the focus pannel still open, pressing f wound up recentering the sun

**Comment by WeirdRubberDuck** [comment] 2023-11-13 14:40
Interesting.  Note that the problem is for any keypress. Not just the F key

**Comment by WeirdRubberDuck** [comment] 2023-11-13 15:08
Actually closed in https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/commit/26e709be4e4b17d7fcdbd8f53cf681f4f4126b29

**Closed** 2023-11-13 15:08 UTC
Labels: Type: Bug, Component: UI, Component: Interaction, Feature: Web UI
