### ISSUE TITLE
Make all webgui panels resizeable

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2793] opened 2023-06-22 08:56 UTC
It is possible to change the size of the SkyBrowser control panel. This would be great for all GUI windows.

https://github.com/OpenSpace/OpenSpace/assets/8808894/aad66808-059b-4a57-8312-72343b84cc71

Discussion in support slack
https://openspacesupport.slack.com/archives/C055D75TJ9K/p1687413355413759

**Comment by ylvaselling** [comment] 2024-03-25 10:00
Duplicate of #3041

**Closed by ylvaselling** 2024-03-25 10:00 UTC
Labels: Type: Enhancement, Component: UI, Feature: Web UI
