### ISSUE TITLE
Projection/aspect/view incorrect on first window if multi-window setup

### ISSUE THREAD

**Issue by eriksunden** [OpenSpace/OpenSpace#1162] opened 2020-05-25 13:36 UTC
When running multiple windows with OpenSpace, the first window will get the wrong projection or view coordinates. It looks like the viewport size is a quarter of what it should be.

This is not an issue in SGCT, as the examples there do not have this problem when using the same config.
![Multi_Window_Same_Projection_On_Both](https://user-images.githubusercontent.com/8737339/82817413-3f766800-9e9d-11ea-9aab-b6c1b11d22b7.jpg)
For reference, the windows in these images have the same FOV, but different "roll" in orientation.
![Multi_Window_Workaround](https://user-images.githubusercontent.com/8737339/82817418-41d8c200-9e9d-11ea-8498-1539b3b6418a.jpg)
A quick workaround is to make the first window not render anything "draw3D=false" and just have the other windows following in the config render the content.

**Comment by alexanderbock** [comment] 2024-01-23 16:17
Closed as duplicate of #507

**Closed by alexanderbock** 2024-01-23 16:17 UTC
Labels: Type: Bug, Component: Core
