### ISSUE TITLE
Globebrowsing add support for reprojecting and adding non global geotiffs

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2107] opened 2022-05-11 02:57 UTC
Right now to add a geotiff, we always run the same two commands using the gdal command line tools.

These tools are build with the same functions that our globebrowsing module us built with, so we could add the same functionality into the globebrowsing module and then we would support geotiff's natively. (At least all the ones that are supported by our default commands).

**Comment by alexanderbock** [comment] 2022-05-21 09:04
Closing as duplicate of #1523

**Closed by alexanderbock** 2022-05-21 09:04 UTC
Labels: Type: Enhancement
