### ISSUE TITLE
Globebrowsing - Combo layer fading improvements

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2392] opened 2022-12-08 19:30 UTC
The notes are "tile provider fade on layer level" and "tile provider fade take master"

the idea being that different parts of the globe are fading at different times, it feels like it would be better if when a layer fades out, it does it for the entire globe and not portions of it. 

Maybe a property could be used to synchronize when it happens.

**Comment by alexanderbock** [comment] 2022-12-09 09:54
Closing as a duplicate of #1241

**Closed by alexanderbock** 2022-12-09 09:54 UTC
