### ISSUE TITLE
Profile editor - Actions and keybinds add duplicate button

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2885] opened 2023-09-11 23:05 UTC
It would be nice to add a duplicate button next to the +/- button for adding new actions.

Often when adding an action like "Turn on mars layers" you would want to add another action for "Turn off mars layers" if we added a duplicate it would save the users a lot of typing.

**Comment by WeirdRubberDuck** [comment] 2023-09-12 07:18
Duplicate of https://github.com/OpenSpace/OpenSpace/issues/2418?

**Closed** 2023-10-03 15:22 UTC
Labels: Type: Enhancement, Component: UI, Feature: Launcher
