### ISSUE TITLE
Time and date GUI: can't input larger values than maximum of slider

### ISSUE THREAD

**Issue by jacobmolin** [OpenSpace/OpenSpace#2149] opened 2022-06-15 18:23 UTC
<< Description of the problem >>
In the time and dates GUI I can't enter a number larger than what is maximum on the slider. For example when "Years" is selected, I double click the "Years/second" box, enter 200 and click outside of the box. The number automatically adjusts to whatever number was there before, since 1 year is the maximum. This is a problem when wanting to look at movement of stars for example. Then we need to move at thousands of year per second. My workaround is to set large deltaTimeSteps with `openspace.time.setDeltaTimeSteps()` via Lua script.

<< What did you expect to happen >>
I would at least like to be able to set years to large numbers, like 100 000. It would also be nice if you can confirm the number entered by pressing Enter instead of having to click outside the box you're entering into.

<< What did happen? >>
Nothing changes when entering a number larger than the maximum of the slider in the GUI.

<< Attach screenshots, if possible >>
<img width="180" alt="image" src="https://user-images.githubusercontent.com/34372356/173897297-48c2b678-cabb-4396-b374-58d70ff0a60a.png">
<img width="180" alt="image" src="https://user-images.githubusercontent.com/34372356/173897374-c407c2ad-87c7-48d4-aa10-79245405f911.png">
<img width="183" alt="image" src="https://user-images.githubusercontent.com/34372356/173897456-42a7d360-cabf-4ea6-8a70-22e14f78c7b7.png">

**Comment by alexanderbock** [comment] 2022-06-28 15:28
We would want all sliders to ignore the min/max values when you manually enter a value, not just for the delta time.
The UI could produce a warning if a user provides a value that is outside of the range

**Comment by WeirdRubberDuck** [comment] 2023-03-01 13:17
Closing as duplicate of #2449 (and it's currently being adressed :) )

**Closed by WeirdRubberDuck** 2023-03-01 13:17 UTC
Labels: Type: Enhancement, Component: UI
