### ISSUE TITLE
the main GUI does not respond to mouse clicks

### ISSUE THREAD

**Issue by antony-liu** [OpenSpace/OpenSpace#1884] opened 2022-02-16 11:02 UTC
The main GUI "Scene / Settings" does not respond to mouse clicks.

![image](https://user-images.githubusercontent.com/1443163/154248715-5156fec9-60cf-4c86-9aea-7c9970599439.png)

The console output is as follow:
![image](https://user-images.githubusercontent.com/1443163/154251274-ca49da4e-a321-4c8b-8201-f2de53fb0761.png)

**Comment by alexanderbock** [comment] 2022-02-16 14:17
Were you building in Debug mode in Visual Studio?  If yes, then this would be a duplicate of https://github.com/OpenSpace/OpenSpace/issues/1857

**Closed** 2022-05-21 11:16 UTC
