### ISSUE TITLE
GUI hint for 'hidden' or 'faded out' items

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3368] opened 2024-08-05 16:07 UTC
It would be nice for the users to be able to see that while something is checked and enabled in the menu (indicating that it should be visible on screen) that it's actually hidden or faded out due a setting in the renderable.

An example would be the SDSS/Tully galaxies or the CMB. 

Other examples might be RenderableLabels, SGN's hidden by TimeFrame, or RenderableGlobe labels component

**Comment by alexanderbock** [comment] 2024-08-06 09:50
Also including the `TimeFrame` status and whether it is current `isReady`

**Comment by alexanderbock** [comment] 2024-08-06 12:09
Closing as duplicate of #528

**Closed by alexanderbock** 2024-08-06 12:09 UTC
Labels: Component: Core, Type: New
