### ISSUE TITLE
Add list of actions into the documentation file

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2945] opened 2023-11-14 13:21 UTC
Right now it is not possible for users to know what actions exist in the current profile.  It would be possible to get a list through `openspace.printInfo(openspace.action.actions())` but it is hard to parse.

It would be easier to read if we added a list of the actions into the generated documentation file

**Comment by ylvaselling** [comment] 2024-02-20 13:10
Duplicate of #2645

**Closed by ylvaselling** 2024-02-20 13:10 UTC
Labels: Type: Maintenance, Component: Documentation
