### ISSUE TITLE
action panel - show bound key

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2336] opened 2022-01-05 16:11 UTC
For actions that have a key bound to them, it would be nice to show that in the button for the action or in the info popover

**Comment by WeirdRubberDuck** [comment] 2022-11-28 16:49
Closing as duplicate of https://github.com/OpenSpace/OpenSpace/issues/2324

**Closed by WeirdRubberDuck** 2022-11-28 16:49 UTC
