### ISSUE TITLE
Star Color problem and possible rendering artifact

### ISSUE THREAD

**Issue by hedbergj** [OpenSpace/OpenSpace#2404] opened 2022-12-15 16:02 UTC
On Default load, Zeta Puppis is not colored correctly. Trying to use the Other Data color option fixes the color, but creates a rendering artifact in all stars with the texture render method. 
![stars-bug](https://user-images.githubusercontent.com/7926907/207908683-56a929a5-abb8-4d2a-ac1a-7e0a4c8ccfad.jpg)

**Comment by WeirdRubberDuck** [comment] 2022-12-19 12:28
Additional reported star
![image](https://user-images.githubusercontent.com/8808894/208426168-d7fb0b69-d6f7-4490-8aa4-5c944a52785c.png)

**Comment by alexanderbock** [comment] 2023-01-26 16:40
Investigate whether the render option is only present on the other data option

**Comment by WeirdRubberDuck** [comment] 2024-05-17 09:13
I was not able to reproduce the erroneous colors, but this commit https://github.com/OpenSpace/OpenSpace/commit/c3657921d2c2e85a6738057c08f9f2ce300a3c3a should have fixed it. The problem was likely due to sampling outside of the valid range for the color map. 

I also could not reproduce the rendering artifact when using the "Other Data" color option, neither in 0.19.2 or 0.20.0. It seems likely that this would have been fixed since the issue was created, however. 

Due to not being able to reproduce it, I'm unable to verify that it is fixed. If someone is able to, I suggest we close it

**Comment by alexanderbock** [comment] 2024-08-23 07:35
It seemed to have fixed it indeed.  Here is another picture:
![win0_000000](https://github.com/user-attachments/assets/1a0b0071-aeef-4d6f-88e8-44230442eae1)

**Closed by alexanderbock** 2024-08-23 07:35 UTC
Labels: Type: Bug, Component: Rendering, Component: Content
