### ISSUE TITLE
Grid improvements

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1009] opened 2019-11-18 22:05 UTC
Right now the grids are made of DUMeshes which require a spec file. It would be nice to have a RenderableGrid which didn't require a speck file.

Also would be nice to have a radial grid in addition to the square one.

**Comment by alexanderbock** [comment] 2019-11-19 11:29
Duplicate of #733

**Closed by alexanderbock** 2019-11-19 11:29 UTC
Labels: Component: Assets, Type: Enhancement, good first issue
