### ISSUE TITLE
make install ignores libLua.so and libSpice.so

### ISSUE THREAD

**Issue by ghost** [OpenSpace/OpenSpace#1076] opened 2020-02-11 11:28 UTC
I'm using Ubuntu 18.04 and run the following procedure to build and install OpenSpace:
```
mkdir OpenSpace/build
cd OpenSpace/build
cmake -DCMAKE_INSTALL_PREFIX=/opt/openspace ..
make -j$(nproc || echo 4)
make install
```

The last stage ignores `libLua.so` and `libSpice.so` so I have to manually copy them to `/opt/openspace/lib`.

**Comment by alexanderbock** [comment] 2020-02-11 12:05
Our installation scripts are still a bit wacky and under construction, particularly on Ubuntu.
Instead of `make install` if you execute `../bin/OpenSpace` does it work to run at least?

Assigning @ElonOlsson  who's our newly minted Linux guy ;)

**Comment by hv-work** [comment] 2020-02-11 12:32
I run build process inside docker container, so it's not easy to run OpenSpace, but at least `ldd` is able to resolve those libs:
```
ldd ../bin/OpenSpace | egrep 'Lua|Spice'
	libSpice.so => /root/OpenSpace/build/ext/spice/libSpice.so (0x00007f1367a1e000)
	libLua.so => /root/OpenSpace/build/ext/ghoul/ext/lua/libLua.so (0x00007f136634b000)
```

**Comment by ElonOlsson** [comment] 2021-03-09 19:29
I was never really the "linux guy"
The account who opened the issue is deleted.
I dont know if the issue is still and issue.
I assigned @GPayne, do you know what this issue is?

**Comment by GPayne** [comment] 2021-03-16 17:38
Closing this for the following reasons:
- Haven't ever experienced this myself or heard other linux users having this problem
- User is trying to do make install, which we don't do for OpenSpace; we just run the executable.
- Original poster's github account has been deleted

**Closed by GPayne** 2021-03-16 17:38 UTC
Labels: Component: Build, OS: Linux
