### ISSUE TITLE
Debug Assertion Failed when compile and run Openspace under Windows 10

### ISSUE THREAD

**Issue by ChengtaoJi** [OpenSpace/OpenSpace#2329] opened 2022-11-22 03:56 UTC
<< Description of the problem >>
I was trying to rotate the OpenSpace with the default gaia profile after compiling successfully under Windows 10, but Debug assertion failed occurs with the following information: 
![image](https://user-images.githubusercontent.com/101535350/203216303-91676700-c4ea-4500-8476-928343915581.png)
When I run Openspace with default or default_full profile, there is no problems.

**Comment by alexanderbock** [comment] 2022-11-22 13:46
Mhh. I can't reproduce it on my end.  If you press "Retry" you should get back into Visual Studio and attach a picture from the Call Stack?  Maybe the breakpoint will also tell us something.
Additionally, could you check `logs/log.html` and see if there are any errors?  If so, would you mind attaching it to this issue?

**Comment by alexanderbock** [comment] 2023-02-21 16:58
Maybe duplicate of #2495?

**Comment by jichengtao** [comment] 2023-02-25 08:54
> Maybe duplicate of #2495?

Yes, they are the same issue.

**Comment by alexanderbock** [comment] 2023-03-14 09:06
Fixed in 15b4cd670f107fcd8bfa7c3b3780abcb20711845

**Closed by alexanderbock** 2023-03-14 09:06 UTC
Labels: Type: Bug, Priority: Critical, Component: Core, Needs more info
