### ISSUE TITLE
Setting Camera Geo State in profile editor does not allow period '.' if the field is empty

### ISSUE THREAD

**Issue by engbergandreas** [OpenSpace/OpenSpace#3320] opened 2024-06-12 09:04 UTC
I tried to change the Geo State on a profile and it would not let me write e.g., 28.609 if the field was empty. It works if there is already a period in the field... Also, we should support the comma ',' for our European peps since 28,609 is not a valid entry in any of the fields. The same seems to be for Navigation State, as well as Scene Graph Node

**Comment by WeirdRubberDuck** [comment] 2024-06-13 08:34
Could you provide a screenshot and/or some steps to reproduce?  I can't reproduce this issue

**Comment by WeirdRubberDuck** [comment] 2024-06-13 08:36
Also, regarding supporting the European comma, we should either make it so that this is supported _everywhere in the system_ (i.e. not only in the profile editor, but when setting values through Lua scripts, or through the WebUI), or not at all, IMO.

**Comment by engbergandreas** [comment] 2024-06-13 08:37
Sure, Profile Editor > Edit (default profile) > Camera Edit > Empty lat/long field, and then try to enter value
for example here, I can't write 121.xxx

![image](https://github.com/OpenSpace/OpenSpace/assets/48772850/5a51558d-a928-4bf3-b3ad-1e014128fe33)

**Comment by engbergandreas** [comment] 2024-06-13 08:40
> Also, regarding supporting the European comma, we should either make it so that this is supported _everywhere in the system_ (i.e. not only in the profile editor, but when setting values through Lua scripts, or through the WebUI), or not at all, IMO.

Yeah I agree with this, and that makes me not want to have it as much. I'm having a hard time seeing how to differentiate a decimal versus two distinct values in a call function for example

**Comment by engbergandreas** [comment] 2024-06-13 08:42
Adding another screenshot here showing that you can add periods if using the already existing one 
![image](https://github.com/OpenSpace/OpenSpace/assets/48772850/021f4375-a05a-4d74-a41a-df343c91140a)

**Comment by engbergandreas** [comment] 2024-06-13 09:20
Just tried on master, same issue sadly :(

**Comment by alexanderbock** [comment] 2024-06-13 09:40
At least for the Lua scripting and JSON we won't be able to have `,` anywhere since their syntax requires a `.` decimal point

**Comment by alexanderbock** [comment] 2024-06-17 14:48
Closing at duplicate of #2596

**Closed by alexanderbock** 2024-06-17 14:48 UTC
Labels: Type: Bug, Component: UI, Component: Core
