### ISSUE TITLE
Ability to add date labels to orbits

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3371] opened 2024-08-06 14:55 UTC
It would be a cool option for RenderableTrailTrajectory to take a list of dates that could be highlighted on the trail. 

(Right now this could be done with a series of Labels that get SpiceTranslations but it could be useful to have as part of the trail class.)

**Comment by alexanderbock** [comment] 2024-08-07 11:28
Closed as duplicate of #86

**Closed by alexanderbock** 2024-08-07 11:28 UTC
Labels: Type: Enhancement, Component: Rendering
