### ISSUE TITLE
Change focus node without changing current camera aim

### ISSUE THREAD

**Issue by emiax** [OpenSpace/OpenSpace#741] opened 2018-10-26 13:41 UTC
I think it would be useful to be able to change the focus node without having the camera pan to the selected object. Examples when this would be useful:

- Zooming out from earth to travel to the moon. Manually find the moon in view. Change focus (without re-aim). Use Ctrl key to manually pan. Zoom in. I think this way of interacting will feel much more "organic" especially in a dome.

- Focusing on an object on a surface, like Curiosity, and then going to free globe-browsing mode. Currently, when you shift focus to Mars, the camera automatically looks down, which may not be what you want.

**Comment by astrodavid** [comment] 2018-10-26 20:03
Wholeheartedly agree!

**Comment by alexanderbock** [comment] 2019-01-09 10:05
Duplicate of #752

**Closed** 2019-05-19 13:58 UTC
Labels: Component: Interaction, Type: Enhancement
