### ISSUE TITLE
Orbital Navigator Speed Limit

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3365] opened 2024-08-05 15:56 UTC
It would be cool to be able to impose a speed limit to the navigator (i.e speed of light, or 17km/s,) so that you could demonstrate different speeds.

I'm not sure if/how this would be split between the zooming and the rotation.

**Comment by alexanderbock** [comment] 2024-08-06 09:47
Closed as duplicate of #1702

**Closed by alexanderbock** 2024-08-06 09:47 UTC
Labels: Type: Enhancement
