### ISSUE TITLE
Individual shader per asset

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1711] opened 2021-08-16 20:31 UTC
Allow shader file to be specified in asset file. Currently filename is hardcoded into c++.

**Comment by alexanderbock** [comment] 2023-10-03 15:45
Either allow the customization on a per-renderable basis or for all Renderables with the ability to selectively disallow individual subclasses

**Comment by alexanderbock** [comment] 2023-10-03 15:45
We wouldn't aim to document the API into the shader and not include it in the versioning of the software

**Comment by alexanderbock** [comment] 2024-08-19 12:45
Closed as duplicate of #2920

**Closed** 2024-08-19 12:45 UTC
Labels: Type: Enhancement, Component: Rendering, Component: Core
