### ISSUE TITLE
Sun glare culling

### ISSUE THREAD

**Issue by carteremmart** [OpenSpace/OpenSpace#1525] opened 2021-03-09 21:49 UTC
Currently the sun's glare is spread out for visual impression of brightness.  The glare is associated with the bright face of the sun, so as an effect, it should only be present when the disk becomes present and not lead in front of it.  Glare should "wink" on or off with the culling of the face of the sun only.   

The "wink" ideally is a fade of the glare proportional to the percentage of the disk of the sun occluded.

![OpenSpace_000000](https://user-images.githubusercontent.com/70605329/110542626-48b48680-80f7-11eb-9e03-9cc821665988.png)
This shows the glare visible when the sun's disk is culled by the Earth being in front of it.  In this case the glare would not be visible.

**Comment by alexanderbock** [comment] 2023-11-28 16:30
Closing as duplicate of #1526

**Closed by alexanderbock** 2023-11-28 16:30 UTC
Labels: Type: Enhancement, Component: Rendering
