### ISSUE TITLE
Horizon Culling is too aggressive when around 0 altitude

### ISSUE THREAD

**Issue by jockekilby** [OpenSpace/OpenSpace#2936] opened 2023-11-07 09:40 UTC
**Describe the bug**
When at or around 0 altitude the horizon culling starts culling away parts of the globe that are still visible near the horizon.

**To Reproduce**
Most easily reproducible with a local high-res VRT but does appear with global maps as well. Look flickering mountains near the horizon while moving around 0 altitude.

**Comment by alexanderbock** [comment] 2023-12-12 16:52
Closed as duplicate of #1272

**Closed by alexanderbock** 2023-12-12 16:52 UTC
Labels: Type: Bug, Priority: Major, Component: Rendering, Feature: GlobeBrowsing
