### ISSUE TITLE
Faulty mapping of "Mars Texture" Layer 

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2251] opened 2022-09-29 07:35 UTC
As reported by user: "I noticed that the Mars Texture image that is stored locally in the sync folder appears to be improperly mapped to the globe, maybe backwards, and doesn't align to the surface features of the other layer sets. "

It does indeed look like it is mapped "backwards". Valles Marineris shows up on the opposite side of the planet compared to e.g. the MOC WA Color layer

**Comment by alexanderbock** [comment] 2022-10-04 15:16
Duplicate of #1895

**Closed by alexanderbock** 2022-10-04 15:16 UTC
Labels: Type: Bug, Component: Content
