### ISSUE TITLE
No UI response when incrementing seconds 

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2651] opened 2023-04-26 14:54 UTC
The display for seconds does not update when clicking the arrows that should increment or decrement seconds.
Works for all the others (years, days, hours, etc)

![image](https://user-images.githubusercontent.com/9076357/234615711-947331be-2478-4023-a478-b2ca421da6ff.png)

**Comment by WeirdRubberDuck** [comment] 2023-04-26 15:23
Some kind of change is happening (try pausing and then changing, got it changing maybe by double clicking). But it's delayed and behaves very weirdly

Note also that the other values are interpolated (over about 5 seconds) when clicking, and set directly when holding shift. Some discussion on expected behavior: for the seconds edit 

- Shift-clicking seconds leads to no change, but the expected behavior would be to immediately increase the second one value

- For the interpolation, what do we want to do? Do we want to interpolate at all? Interpolating one second over 5 seconds is maybe a bit weird

**Comment by WeirdRubberDuck** [comment] 2023-04-26 15:25
Also note that the correct API calls are being called from the webpage when clicking. So the problem might be either on the C++ side, or related to subscribing to the changed value in the GUI

![image](https://user-images.githubusercontent.com/8808894/234624366-51fb993b-a39b-4054-8a97-0415461957e7.png)

**Comment by Arohdin** [comment] 2023-04-26 15:47
> - For the interpolation, what do we want to do? Do we want to interpolate at all? Interpolating one second over 5 seconds is maybe a bit weird

In my opinion, when changing seconds using the GUI normal click and shift-click should behave the same - instant change.

**Comment by ylvaselling** [comment] 2023-04-27 17:04
I think the problem was due to me capping the time in the Redux state. This is now removed and I can't reproduce the bug so closing this. If we want to interpolate or not is probably another discussion
 
https://user-images.githubusercontent.com/24265984/234936626-fa05a837-6c62-42e3-b463-c4190ba86772.mp4

**Closed by ylvaselling** 2023-04-27 17:04 UTC
Labels: Type: Bug, Component: UI, Feature: Web UI

**Comment by ylvaselling** [comment] 2023-04-27 17:07
Make a new issue #2661
