### ISSUE TITLE
Scale from GUI seem to be applied to boundingsphere twice

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2616] opened 2023-04-14 11:31 UTC
Apparent when changing the scale of the current focus node from the GUI ; the camera is then pushed out to a distance that is much farther away (to me looks likely that it could be a squared value of either the scale or the bounding sphere) from the object. When Going closer and then trying to fly to the object, the camera path system also complains that "Camera is within the bounding sphere of the target node"

So, the `boundingSphere()` function of the Scene graph node probably returns too large a value. 

Observed for RenderableGlobes, but is likely the case for more objects

**Comment by WeirdRubberDuck** [comment] 2023-04-14 11:31
Should also investigate potential problems with the interaction sphere, but as the camera can be moved manually closer to the object it seems like that should not be an issue

**Comment by alexanderbock** [comment] 2023-05-30 15:39
Duplicate of #2707

**Closed by alexanderbock** 2023-05-30 15:39 UTC
Labels: Type: Bug, Component: Core
