### ISSUE TITLE
Session recording doesn't play back when "Output frames" is selected

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2718] opened 2023-05-26 16:10 UTC
Expected behavior is that the playback starts when you press play
https://github.com/OpenSpace/OpenSpace/assets/24265984/fc12e9ee-bae6-444e-bf29-0c7a6d95681e

Console:
`
(I) SessionRecording     Finished parsing 1306 entries from playback file C:\OpenSpace\user\recordings\shobadoo.osrec
(D) OpenSpaceEngine      Mode: SessionRecording
(I) SessionRecording     Playback session started: (2887.680,0.0,705487189.857) with 1304/0/2 entries, forceTime=1
(I) SessionRecording     Playback finished signal: script
`

Scriptlog:
`
return openspace.sessionRecording.enableTakeScreenShotDuringPlayback(60)
return openspace.sessionRecording.startPlayback("testing.osrec",false)
openspace.time.setPause(false)
openspace.time.setDeltaTime(1)
`

**Comment by alexanderbock** [comment] 2023-06-01 07:55
Closing as duplicate of #2593

**Closed by alexanderbock** 2023-06-01 07:55 UTC
Labels: Type: Bug, Priority: Critical, Component: Core, Feature: Session Recording, RC
