### ISSUE TITLE
Insight position is wrong after the end of the spice kernel

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1380] opened 2020-11-16 13:51 UTC
When starting up the Mars scene, the Insight lander is placed in the Sun as the SPICE kernel information is exceeded.  Maybe a Timelinetranslation that will fix the position to the last known position?

As reported by Jacob R

**Comment by micahnyc** [comment] 2021-01-27 01:38
Related to: https://github.com/OpenSpace/OpenSpace/issues/1380 (i.e start vs end of spice values.)

**Comment by micahnyc** [comment] 2021-03-12 17:22
closing as dupe of https://github.com/OpenSpace/OpenSpace/issues/1056

**Closed by micahnyc** 2021-03-12 17:22 UTC
Labels: Component: Content, Type: Bug
