### ISSUE TITLE
Vertical config

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2383] opened 2022-12-08 16:24 UTC
It would be nice to provide a vertical config file that makes it easy to create content for social media

**Comment by GPayne** [comment] 2023-03-15 18:38
This will depend on issue #2546 getting fixed.

**Comment by GPayne** [comment] 2023-03-20 04:40
There is a PR for issue #2546 now, but actually this issue isn't dependent on it (despite my comment above). Switching the resolution in single.json to 720x1280 works for a simple portrait window.
However, if the window is taller than the vertical resolution of the display, then the window appears with the rendering compressed (notice the empty black space at top of the window). This is not due to the window config GUI; the issue is within the SGCT code.
![too-tall_window](https://user-images.githubusercontent.com/3966290/226248334-7fb5ce28-5557-44b3-bdc4-82fccc2ca1ca.png)

I wanted to mention this since it might cause confusion for a user on a 1080p monitor, for example.

**Comment by GPayne** [comment] 2023-06-09 17:10
Closed in commit 9c6be7a

**Closed by GPayne** 2023-06-09 17:10 UTC
Labels: Component: Core, Type: New
