### ISSUE TITLE
Automatic selection of projection type is not recognizing AMNH as a fisheye projection.

### ISSUE THREAD

**Issue by jccosta** [OpenSpace/OpenSpace#619] opened 2018-06-08 14:36 UTC
We must have a way to tell OS that the labels rendering must be done using the camera position orientation.

**Comment by alexanderbock** [comment] 2018-06-09 17:01
Hayden is not rendering as fisheye;  each projector is rendering as flat-screen by themselves

**Comment by alexanderbock** [comment] 2022-05-21 13:23
Closing as duplicate of #2099

**Closed by alexanderbock** 2022-05-21 13:23 UTC
