### ISSUE TITLE
OpenSpace crashes if multiple RenderableModelProjections use the same resource

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#1633] opened 2021-06-04 19:58 UTC
### What Happens:
If two RenderableModelProjections in an asset both reference the same sync resource, then OpenSpace will crash without logging any warnings or errors.

### Expected Behavior:
Having two scene graph nodes reference the same resource is not expected. However, OpenSpace should fail gracefully with a log error describing the problem.

### Steps to Reproduce:

1. Edit **solarsystem/missions/osirisrex/bennu_projection.asset**
2. Copy the entire `BennuProjection{ }` table and paste afterward to create a duplicate table.
3. Rename the new table as `local Bennu2`, and rename its identifier key (`Identifier = "Bennu2",`). Now both objects reference the same sync resources in their Sequence key.
5. Add the duplicate `Bennu2` to the scene graph nodes list at the end of the file: `assetHelper.registerSceneGraphNodesAndExport(asset, { BennuProjection, Bennu2, BennuTrail })`
6. Save and run the osirisrex profile in OpenSpace

**Comment by alexanderbock** [comment] 2021-06-06 08:24
Closing this as a duplicate of #898

**Closed by alexanderbock** 2021-06-06 08:24 UTC
Labels: Component: Assets

**Comment by alexanderbock** [comment] 2021-06-06 08:25
The solution we are using everywhere is to have the synchronization in a separate asset file that gets `require`d from multiple places.  Since assets only get initialized once, the problem doesn't manifest then
